In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
import string

In [2]:
def gen_transition_matrix(transitions,n):
    M = np.zeros((5,5))
    
    
    for (i,j) in zip(transitions,transitions[1:]):
        M[i][j] += 1
        #print(M[i][j])
    #now convert to probabilities:
    for row in M:
        s = sum(row)
        
        if s > 0:
            row[:] = [f/s for f in row]
    return M

#test:

#t = [0,0,1,0,2,0,3,0,4,1,1,2,1,3,1,4,2,2,3,2,4,3,3,4,4,0]
t = [0,0,1,0,0,2,0,3,4,0,3,4,0,4,1,2,2,1,3,1,4,2,2,3,2,4,3,3,4,4,0]
n = max(t)+1
print(f"Max no of states: {n}")
m = gen_transition_matrix(t,n)
for row in m: print(' '.join('{0:.2f}'.format(x) for x in row))

Max no of states: 5
0.29 0.14 0.14 0.29 0.14
0.25 0.00 0.25 0.25 0.25
0.17 0.17 0.33 0.17 0.17
0.00 0.17 0.17 0.17 0.50
0.43 0.14 0.14 0.14 0.14


In [3]:

jar_1 =[]
jar_2 =[]
jar_3 =[]
jar_4 =[]
jar_5 =[]
# 0 = RED, 1 = Green , 2=Blue
'''def create_jar():
    n= random.randint(20,30)
    jar=[]
    for count in range(n):
        jar.append(random.randint(0,2))
    return jar
 '''
  
jar_1 = [random.choice('RGB') for _ in range(random.randint(20,30))] 
jar_2 = [random.choice('RGB') for _ in range(random.randint(20,30))]
jar_3 =[random.choice('RGB') for _ in range(random.randint(20,30))]
jar_4=[random.choice('RGB') for _ in range(random.randint(20,30))]
jar_5=[random.choice('RGB') for _ in range(random.randint(20,30))]
print(f"{jar_1} \n {jar_2} \n {jar_3} \n{jar_4}\n{jar_4}\n{jar_5}")

['G', 'G', 'B', 'B', 'R', 'R', 'G', 'R', 'G', 'G', 'R', 'G', 'G', 'R', 'B', 'B', 'B', 'B', 'G', 'B', 'G', 'R', 'G', 'G', 'B', 'R', 'R', 'G'] 
 ['R', 'R', 'G', 'B', 'B', 'G', 'B', 'R', 'B', 'R', 'B', 'R', 'R', 'G', 'B', 'G', 'R', 'B', 'B', 'R', 'G', 'B', 'G', 'R'] 
 ['B', 'G', 'R', 'B', 'B', 'B', 'B', 'B', 'R', 'B', 'R', 'R', 'B', 'B', 'G', 'R', 'B', 'B', 'G', 'G', 'G', 'G', 'R', 'B', 'R'] 
['R', 'R', 'B', 'G', 'R', 'R', 'B', 'R', 'B', 'B', 'B', 'G', 'B', 'G', 'R', 'G', 'G', 'R', 'B', 'B', 'B', 'B', 'R']
['R', 'R', 'B', 'G', 'R', 'R', 'B', 'R', 'B', 'B', 'B', 'G', 'B', 'G', 'R', 'G', 'G', 'R', 'B', 'B', 'B', 'B', 'R']
['B', 'G', 'G', 'G', 'B', 'R', 'G', 'R', 'G', 'R', 'G', 'B', 'B', 'B', 'B', 'R', 'R', 'B', 'G', 'R', 'G']


In [4]:
B=np.zeros((5,3))
#print(B)
def count_prob(jar,i):
   total = len(jar)
   red= jar.count('R')
   green= jar.count('G')
   blue= jar.count('B')
   probR = red/total
   probG = green/total
   probb =blue/total
   B[i][0]=probR
   B[i][1]=probG
   B[i][2]=probb
   print(f"Probability :  P(R) :{probR}, P(G) :{probG} , P(B) :{probb}")
    
count_prob(jar_1,0)
count_prob(jar_2,1)
count_prob(jar_3,2)
count_prob(jar_4,3)
count_prob(jar_5,4)
print(B)

Probability :  P(R) :0.2857142857142857, P(G) :0.42857142857142855 , P(B) :0.2857142857142857
Probability :  P(R) :0.375, P(G) :0.25 , P(B) :0.375
Probability :  P(R) :0.28, P(G) :0.24 , P(B) :0.48
Probability :  P(R) :0.34782608695652173, P(G) :0.21739130434782608 , P(B) :0.43478260869565216
Probability :  P(R) :0.2857142857142857, P(G) :0.38095238095238093 , P(B) :0.3333333333333333
[[0.28571429 0.42857143 0.28571429]
 [0.375      0.25       0.375     ]
 [0.28       0.24       0.48      ]
 [0.34782609 0.2173913  0.43478261]
 [0.28571429 0.38095238 0.33333333]]


In [5]:
#initial State
states =['jar_1','jar_2','jar_3','jar_4','jar_5']
initial_state_pi = random.choice(states)
print(initial_state_pi)

jar_4


In [35]:
O = [random.randrange(0,3) for _ in range(5)]
print(O)

[1, 0, 0, 1, 1]


In [ ]:
from re import T


def forward(O, a, b, pi):
    N = a.shape[0]
    T = O.shape[0]
    alpha = np.zeros((T,N))

    alpha[0, :] = pi * b[:, O[0]]
    for i in range(N):
         alpha[0, i] = pi[i] * b[i, O[0]]
 
    for t in range(1, O.shape[0]):
        for j in range(a.shape[0]):
            # Matrix Computation Steps
            #                  ((1x2) . (1x2))      *     (1)
            #                        (1)            *     (1)
            alpha[t, j] = alpha[t - 1].dot(a[:, j]) * b[j, O[t]]
 
    return alpha